---
- name: HomeLab | Vault certificate template
  ansible.builtin.template:
    src: "templates/certificate.tmpl"
    dest: "/etc/vault.d/cert-{{ certificate.name }}.tmpl"
    variable_start_string: "<<"
    variable_end_string: ">>"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0664"
  notify: Restart Vault Agent

- name: HomeLab | Vault certificate configuration
  ansible.builtin.blockinfile:
    path: "/etc/vault.d/vault-agent.hcl"
    create: true
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0664"
    marker: "# {mark} CERTIFICATE {{ certificate.name | upper }}"
    block: |
      template {
        source      = "/etc/vault.d/cert-{{ certificate.name }}.tmpl"
        destination = "{{ certificate.cert_file }}"
      }
  notify: Restart Vault Agent
