---
- name: HomeLab | Vault variables
  ansible.builtin.set_fact:
    cert:
      name: "{{ certificate.name }}"
      common_name: "{{ certificate.common_name }}"
      alt_names: "{{ certificate.alt_names | default({}) }}"
      ip_sans: "{{ certificate.ip_sans | default({}) }}"
      cert_file: "{{ certificate.cert_file }}"
      key_file: "{{ certificate.key_file }}"
      ca_file: "{{ certificate.ca_file }}"
      policy: '{{ certificate["policy"] | default("server_cert") }}'
      ttl: '{{ certificate["ttl"] | default("24h") }}'
      owner: '{{ certificate["owner"] | default("") }}'
      group: '{{ certificate["group"] | default("") }}'

- name: HomeLab | Vault certificate template
  ansible.builtin.template:
    src: "templates/certificate.tmpl"
    dest: "/etc/vault.d/cert-{{ cert.name }}.tmpl"
    variable_start_string: "<<"
    variable_end_string: ">>"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0664"
  notify: Restart Vault Agent

- name: HomeLab | Vault certificate configuration
  ansible.builtin.blockinfile:
    path: "/etc/vault.d/vault-agent.hcl"
    create: true
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0664"
    marker: "# {mark} CERTIFICATE {{ cert.name | upper }}"
    block: |
      template {
        source      = "/etc/vault.d/cert-{{ cert.name }}.tmpl"
        destination = "{{ cert.cert_file }}"
      }
  notify: Restart Vault Agent
